Index: git/Makefile
===================================================================
--- git.orig/Makefile
+++ git/Makefile
@@ -5,7 +5,7 @@ INCPATHS=../libmcp23s17/src/
 LIBPATHS=../libmcp23s17/
 LDFLAGS=
 CFLAGS=-c -Wall
-CC=gcc
+CC=$(CC)
 SWIG=swig
 
 # ------------ MAGIC BEGINS HERE -------------
@@ -42,10 +42,10 @@ distclean: clean
 	rm -f $(BINARY)
 
 example: example.c
-	gcc -o example example.c -Isrc/ -L. -lpifacedigital -L../libmcp23s17/ -lmcp23s17
+	$(CC) -o example example.c -Isrc/ -L. -lpifacedigital -L../libmcp23s17/ -lmcp23s17
 
 pifacedigital: util/pifacedigital-cmd.c
-	gcc -o pifacedigital util/pifacedigital-cmd.c -Isrc/ -I../libmcp23s17/src/ -L. -lpifacedigital -L../libmcp23s17/ -lmcp23s17
+	$(CC) -o pifacedigital util/pifacedigital-cmd.c -Isrc/ -I../libmcp23s17/src/ -L. -lpifacedigital -L../libmcp23s17/ -lmcp23s17
 
 clean:
 	rm -f $(OBJECTS)
